SELECT YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(U.USER_ID)
                                           FROM USER_INFO AS U
                                           WHERE JOINED LIKE '2021%') ,1) AS PUCHASED_RATIO
FROM USER_INFO AS U
INNER JOIN ONLINE_SALE AS S
ON U.USER_ID=S.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH