SELECT USER_ID, PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) as sale_count
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING sale_count >= 2
) AS subquery
ORDER BY USER_ID, PRODUCT_ID DESC;
